version: "3.8"

services: 
  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 50051:50051
    env_file: 
      - ./.env
    depends_on:
      - cache
      - db
      - search
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  db:
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_locks_per_transaction=1024" #increased to consolidate partitioning
    ports:
      - 5433:5432
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  cache:
    image: redis:latest
    command: bash -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports: 
      - 6379:6379
    env_file: 
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - node.name=search
      - cluster.name=okapi
      - cluster.initial_master_nodes=search
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    logging:
      driver: "json-file"
      options:
        max-size: "10m"