version: "3.8"

services: 
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 4000:3000
      - 50051:50051
    env_file: 
      - ./.env
    depends_on:
      - cache
      - db
      - search
      - proxy
  db:
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_locks_per_transaction=1024" #increased to consolidate partitioning
    ports:
      - 5433:5432
    env_file:
      - ./.env
  proxy:
    image: okapis/proxy:1.0
    ports:
      - 4040:4040
    env_file: 
    - ./.env    
  cache:
    image: redis:latest
    command: bash -c "redis-server --requirepass ${CACHE_PASSWORD}"
    ports: 
      - 6379:6379
    env_file: 
      - ./.env
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - node.name=search
      - cluster.name=okapi
      - cluster.initial_master_nodes=search
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  log:
    image: graylog/graylog:3.3
    env_file:
      - ./.env
    depends_on:
      - log_db
      - elasticsearch
    ports:
      # Web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
  log_db:
    image: mongo:4.2
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g